import {
	HairStyle,
	ShortHairStyle,
	NeckHairStyle,
	ShoulderHairStyle,
	HairAccessory,
} from "./types/hair";
import { Color } from "./types/color";

// GENERIC
export const PHYSICAL_GENDER = ["male", "female", "hermaphrodite"];
export const APPEARANCE = ["masculine", "feminine", "androgynous"];
export const HEIGHT = [
	"average",
	"tall",
	"short",
	"above-average",
	"below-average",
];
export const VOICE = [
	"melodic",
	"high-pitched",
	"unpleasant",
	"pleasant",
	"mellow",
	"low",
	"relaxed",
	"emotionless",
	"cold",
	"piercing",
	"serious",
];
export const COLORS = [
	new Color("Black", "000000"),
	new Color("Night", "0C090A"),
	new Color("Gunmetal", "2C3539"),
	new Color("Midnight", "2B1B17"),
	new Color("Charcoal", "34282C"),
	new Color("Dark Slate Grey", "25383C"),
	new Color("Oil", "3B3131"),
	new Color("Black Cat", "413839"),
	new Color("Iridium", "3D3C3A"),
	new Color("Black Eel", "463E3F"),
	new Color("Black Cow", "4C4646"),
	new Color("Gray Wolf", "504A4B"),
	new Color("Vampire Gray", "565051"),
	new Color("Gray Dolphin", "5C5858"),
	new Color("Carbon Gray", "625D5D"),
	new Color("Ash Gray", "666362"),
	new Color("Cloudy Gray", "6D6968"),
	new Color("Smokey Gray", "726E6D"),
	new Color("Gray", "736F6E"),
	new Color("Granite", "837E7C"),
	new Color("Battleship Gray", "848482"),
	new Color("Gray Cloud", "B6B6B4"),
	new Color("Gray Goose", "D1D0CE"),
	new Color("Platinum", "E5E4E2"),
	new Color("Metallic Silver", "BCC6CC"),
	new Color("Blue Gray", "98AFC7"),
	new Color("Light Slate Gray", "6D7B8D"),
	new Color("Slate Gray", "657383"),
	new Color("Jet Gray", "616D7E"),
	new Color("Mist Blue", "646D7E"),
	new Color("Marble Blue", "566D7E"),
	new Color("Slate Blue", "737CA1"),
	new Color("Steel Blue", "4863A0"),
	new Color("Blue Jay", "2B547E"),
	new Color("Dark Slate Blue", "2B3856"),
	new Color("Midnight Blue", "151B54"),
	new Color("Navy Blue", "000080"),
	new Color("Blue Whale", "342D7E"),
	new Color("Lapis Blue", "15317E"),
	new Color("Denim Dark Blue", "151B8D"),
	new Color("Earth Blue", "0000A0"),
	new Color("Cobalt Blue", "0020C2"),
	new Color("Blueberry Blue", "0041C2"),
	new Color("Sapphire Blue", "2554C7"),
	new Color("Blue Eyes", "1569C7"),
	new Color("Royal Blue", "2B60DE"),
	new Color("Blue Orchid", "1F45FC"),
	new Color("Blue Lotus", "6960EC"),
	new Color("Light Slate Blue", "736AFF"),
	new Color("Windows Blue", "357EC7"),
	new Color("Glacial Blue Ice", "368BC1"),
	new Color("Silk Blue", "488AC7"),
	new Color("Blue Ivy", "3090C7"),
	new Color("Blue Koi", "659EC7"),
	new Color("Columbia Blue", "87AFC7"),
	new Color("Baby Blue", "95B9C7"),
	new Color("Light Steel Blue", "728FCE"),
	new Color("Ocean Blue", "2B65EC"),
	new Color("Blue Ribbon", "306EFF"),
	new Color("Blue Dress", "157DEC"),
	new Color("Dodger Blue", "1589FF"),
	new Color("Cornflower Blue", "6495ED"),
	new Color("Sky Blue", "6698FF"),
	new Color("Butterfly Blue", "38ACEC"),
	new Color("Iceberg", "56A5EC"),
	new Color("Crystal Blue", "5CB3FF"),
	new Color("Deep Sky Blue", "3BB9FF"),
	new Color("Denim Blue", "79BAEC"),
	new Color("Light Sky Blue", "82CAFA"),
	new Color("Day Sky Blue", "82CAFF"),
	new Color("Jeans Blue", "A0CFEC"),
	new Color("Blue Angel", "B7CEEC"),
	new Color("Pastel Blue", "B4CFEC"),
	new Color("Sea Blue", "C2DFFF"),
	new Color("Powder Blue", "C6DEFF"),
	new Color("Coral Blue", "AFDCEC"),
	new Color("Light Blue", "ADDFFF"),
	new Color("Robin Egg Blue", "BDEDFF"),
	new Color("Pale Blue Lily", "CFECEC"),
	new Color("Light Cyan", "E0FFFF"),
	new Color("Water", "EBF4FA"),
	new Color("Alice Blue", "F0F8FF"),
	new Color("Azure", "F0FFFF"),
	new Color("Light Slate", "CCFFFF"),
	new Color("Light Aquamarine", "93FFE8"),
	new Color("Electric Blue", "9AFEFF"),
	new Color("Aquamarine", "7FFFD4"),
	new Color("Cyan or Aqua", "00FFFF"),
	new Color("Tron Blue", "7DFDFE"),
	new Color("Blue Zircon", "57FEFF"),
	new Color("Blue Lagoon", "8EEBEC"),
	new Color("Celeste", "50EBEC"),
	new Color("Blue Diamond", "4EE2EC"),
	new Color("Tiffany Blue", "81D8D0"),
	new Color("Cyan Opaque", "92C7C7"),
	new Color("Blue Hosta", "77BFC7"),
	new Color("Northern Lights Blue", "78C7C7"),
	new Color("Medium Turquoise", "48CCCD"),
	new Color("Turquoise", "43C6DB"),
	new Color("Jellyfish", "46C7C7"),
	new Color("Blue green", "7BCCB5"),
	new Color("Macaw Blue Green", "43BFC7"),
	new Color("Light Sea Green", "3EA99F"),
	new Color("Dark Turquoise", "3B9C9C"),
	new Color("Sea Turtle Green", "438D80"),
	new Color("Medium Aquamarine", "348781"),
	new Color("Greenish Blue", "307D7E"),
	new Color("Grayish Turquoise", "5E7D7E"),
	new Color("Beetle Green", "4C787E"),
	new Color("Teal", "008080"),
	new Color("Camouflage Green", "4E8975"),
	new Color("Sage Green", "848b79"),
	new Color("Hazel Green", "617C58"),
	new Color("Venom Green", "728C00"),
	new Color("Fern Green", "667C26"),
	new Color("Dark Forest Green", "254117"),
	new Color("Medium Sea Green", "306754"),
	new Color("Medium Forest Green", "347235"),
	new Color("Seaweed Green", "437C17"),
	new Color("Pine Green", "387C44"),
	new Color("Jungle Green", "347C2C"),
	new Color("Shamrock Green", "347C17"),
	new Color("Medium Spring Green", "348017"),
	new Color("Forest Green", "4E9258"),
	new Color("Green Onion", "6AA121"),
	new Color("Spring Green", "4AA02C"),
	new Color("Lime Green", "41A317"),
	new Color("Clover Green", "3EA055"),
	new Color("Green Snake", "6CBB3C"),
	new Color("Alien Green", "6CC417"),
	new Color("Green Apple", "4CC417"),
	new Color("Yellow Green", "52D017"),
	new Color("Kelly Green", "4CC552"),
	new Color("Zombie Green", "54C571"),
	new Color("Frog Green", "99C68E"),
	new Color("Green Peas", "89C35C"),
	new Color("Dollar Bill Green", "85BB65"),
	new Color("Dark Sea Green", "8BB381"),
	new Color("Iguana Green", "9CB071"),
	new Color("Avocado Green", "B2C248"),
	new Color("Pistachio Green", "9DC209"),
	new Color("Salad Green", "A1C935"),
	new Color("Hummingbird Green", "7FE817"),
	new Color("Nebula Green", "59E817"),
	new Color("Stoplight Go Green", "57E964"),
	new Color("Algae Green", "64E986"),
	new Color("Jade Green", "5EFB6E"),
	new Color("Green", "00FF00"),
	new Color("Emerald Green", "5FFB17"),
	new Color("Lawn Green", "87F717"),
	new Color("Chartreuse", "8AFB17"),
	new Color("Dragon Green", "6AFB92"),
	new Color("Mint green", "98FF98"),
	new Color("Green Thumb", "B5EAAA"),
	new Color("Light Jade", "C3FDB8"),
	new Color("Tea Green", "CCFB5D"),
	new Color("Green Yellow", "B1FB17"),
	new Color("Slime Green", "BCE954"),
	new Color("Goldenrod", "EDDA74"),
	new Color("Harvest Gold", "EDE275"),
	new Color("Sun Yellow", "FFE87C"),
	new Color("Yellow", "FFFF00"),
	new Color("Corn Yellow", "FFF380"),
	new Color("Parchment", "FFFFC2"),
	new Color("Cream", "FFFFCC"),
	new Color("Lemon Chiffon", "FFF8C6"),
	new Color("Cornsilk", "FFF8DC"),
	new Color("Beige", "F5F5DC"),
	new Color("Blonde", "FBF6D9"),
	new Color("Antique White", "FAEBD7"),
	new Color("Champagne", "F7E7CE"),
	new Color("Blanched Almond", "FFEBCD"),
	new Color("Vanilla", "F3E5AB"),
	new Color("Tan Brown", "ECE5B6"),
	new Color("Peach", "FFE5B4"),
	new Color("Mustard", "FFDB58"),
	new Color("Rubber Ducky Yellow", "FFD801"),
	new Color("Bright Gold", "FDD017"),
	new Color("Golden brown", "EAC117"),
	new Color("Macaroni and Cheese", "F2BB66"),
	new Color("Saffron", "FBB917"),
	new Color("Beer", "FBB117"),
	new Color("Cantaloupe", "FFA62F"),
	new Color("Bee Yellow", "E9AB17"),
	new Color("Brown Sugar", "E2A76F"),
	new Color("Burly Wood", "DEB887"),
	new Color("Deep Peach", "FFCBA4"),
	new Color("Ginger Brown", "C9BE62"),
	new Color("School Bus Yellow", "E8A317"),
	new Color("Sandy Brown", "EE9A4D"),
	new Color("Fall Leaf Brown", "C8B560"),
	new Color("Orange Gold", "D4A017"),
	new Color("Sand", "C2B280"),
	new Color("Cookie Brown", "C7A317"),
	new Color("Caramel", "C68E17"),
	new Color("Brass", "B5A642"),
	new Color("Khaki", "ADA96E"),
	new Color("Camel brown", "C19A6B"),
	new Color("Bronze", "CD7F32"),
	new Color("Tiger Orange", "C88141"),
	new Color("Cinnamon", "C58917"),
	new Color("Bullet Shell", "AF9B60"),
	new Color("Dark Goldenrod", "AF7817"),
	new Color("Copper", "B87333"),
	new Color("Wood", "966F33"),
	new Color("Oak Brown", "806517"),
	new Color("Moccasin", "827839"),
	new Color("Army Brown", "827B60"),
	new Color("Sandstone", "786D5F"),
	new Color("Mocha", "493D26"),
	new Color("Taupe", "483C32"),
	new Color("Coffee", "6F4E37"),
	new Color("Brown Bear", "835C3B"),
	new Color("Red Dirt", "7F5217"),
	new Color("Sepia", "7F462C"),
	new Color("Orange Salmon", "C47451"),
	new Color("Rust", "C36241"),
	new Color("Red Fox", "C35817"),
	new Color("Chocolate", "C85A17"),
	new Color("Sedona", "CC6600"),
	new Color("Papaya Orange", "E56717"),
	new Color("Halloween Orange", "E66C2C"),
	new Color("Pumpkin Orange", "F87217"),
	new Color("Construction Cone Orange", "F87431"),
	new Color("Sunrise Orange", "E67451"),
	new Color("Mango Orange", "FF8040"),
	new Color("Dark Orange", "F88017"),
	new Color("Coral", "FF7F50"),
	new Color("Basket Ball Orange", "F88158"),
	new Color("Light Salmon", "F9966B"),
	new Color("Tangerine", "E78A61"),
	new Color("Dark Salmon", "E18B6B"),
	new Color("Light Coral", "E77471"),
	new Color("Bean Red", "F75D59"),
	new Color("Valentine Red", "E55451"),
	new Color("Shocking Orange", "E55B3C"),
	new Color("Red", "FF0000"),
	new Color("Scarlet", "FF2400"),
	new Color("Ruby Red", "F62217"),
	new Color("Ferrari Red", "F70D1A"),
	new Color("Fire Engine Red", "F62817"),
	new Color("Lava Red", "E42217"),
	new Color("Love Red", "E41B17"),
	new Color("Grapefruit", "DC381F"),
	new Color("Chestnut Red", "C34A2C"),
	new Color("Cherry Red", "C24641"),
	new Color("Mahogany", "C04000"),
	new Color("Chilli Pepper", "C11B17"),
	new Color("Cranberry", "9F000F"),
	new Color("Red Wine", "990012"),
	new Color("Burgundy", "8C001A"),
	new Color("Chestnut", "954535"),
	new Color("Blood Red", "7E3517"),
	new Color("Sienna", "8A4117"),
	new Color("Sangria", "7E3817"),
	new Color("Firebrick", "800517"),
	new Color("Maroon", "810541"),
	new Color("Plum Pie", "7D0541"),
	new Color("Velvet Maroon", "7E354D"),
	new Color("Plum Velvet", "7D0552"),
	new Color("Rosy Finch", "7F4E52"),
	new Color("Puce", "7F5A58"),
	new Color("Dull Purple", "7F525D"),
	new Color("Rosy Brown", "B38481"),
	new Color("Khaki Rose", "C5908E"),
	new Color("Pink Bow", "C48189"),
	new Color("Lipstick Pink", "C48793"),
	new Color("Rose", "E8ADAA"),
	new Color("Rose Gold", "ECC5C0"),
	new Color("Desert Sand", "EDC9AF"),
	new Color("Pig Pink", "FDD7E4"),
	new Color("Cotton Candy", "FCDFFF"),
	new Color("Pink Bubble Gum", "FFDFDD"),
	new Color("Misty Rose", "FBBBB9"),
	new Color("Pink", "FAAFBE"),
	new Color("Light Pink", "FAAFBA"),
	new Color("Flamingo Pink", "F9A7B0"),
	new Color("Pink Rose", "E7A1B0"),
	new Color("Pink Daisy", "E799A3"),
	new Color("Cadillac Pink", "E38AAE"),
	new Color("Carnation Pink", "F778A1"),
	new Color("Blush Red", "E56E94"),
	new Color("Hot Pink", "F660AB"),
	new Color("Watermelon Pink", "FC6C85"),
	new Color("Violet Red", "F6358A"),
	new Color("Deep Pink", "F52887"),
	new Color("Pink Cupcake", "E45E9D"),
	new Color("Pink Lemonade", "E4287C"),
	new Color("Neon Pink", "F535AA"),
	new Color("Magenta", "FF00FF"),
	new Color("Dimorphotheca Magenta", "E3319D"),
	new Color("Bright Neon Pink", "F433FF"),
	new Color("Pale Violet Red", "D16587"),
	new Color("Tulip Pink", "C25A7C"),
	new Color("Medium Violet Red", "CA226B"),
	new Color("Rogue Pink", "C12869"),
	new Color("Burnt Pink", "C12267"),
	new Color("Bashful Pink", "C25283"),
	new Color("Dark Carnation Pink", "C12283"),
	new Color("Plum", "B93B8F"),
	new Color("Viola Purple", "7E587E"),
	new Color("Purple Iris", "571B7E"),
	new Color("Plum Purple", "583759"),
	new Color("Indigo", "4B0082"),
	new Color("Purple Monster", "461B7E"),
	new Color("Purple Haze", "4E387E"),
	new Color("Eggplant", "614051"),
	new Color("Grape", "5E5A80"),
	new Color("Purple Jam", "6A287E"),
	new Color("Dark Orchid", "7D1B7E"),
	new Color("Purple Flower", "A74AC7"),
	new Color("Medium Orchid", "B048B5"),
	new Color("Purple Amethyst", "6C2DC7"),
	new Color("Dark Violet", "842DCE"),
	new Color("Violet", "8D38C9"),
	new Color("Purple Sage Bush", "7A5DC7"),
	new Color("Lovely Purple", "7F38EC"),
	new Color("Purple", "8E35EF"),
	new Color("Aztec Purple", "893BFF"),
	new Color("Medium Purple", "8467D7"),
	new Color("Jasmine Purple", "A23BEC"),
	new Color("Purple Daffodil", "B041FF"),
	new Color("Tyrian Purple", "C45AEC"),
	new Color("Crocus Purple", "9172EC"),
	new Color("Purple Mimosa", "9E7BFF"),
	new Color("Heliotrope Purple", "D462FF"),
	new Color("Crimson", "E238EC"),
	new Color("Purple Dragon", "C38EC7"),
	new Color("Lilac", "C8A2C8"),
	new Color("Blush Pink", "E6A9EC"),
	new Color("Mauve", "E0B0FF"),
	new Color("Wisteria Purple", "C6AEC7"),
	new Color("Blossom Pink", "F9B7FF"),
	new Color("Thistle", "D2B9D3"),
	new Color("Periwinkle", "E9CFEC"),
	new Color("Lavender Pinocchio", "EBDDE2"),
	new Color("Lavender blue", "E3E4FA"),
	new Color("Pearl", "FDEEF4"),
	new Color("Sea Shell", "FFF5EE"),
	new Color("Milk White", "FEFCFF"),
	new Color("White", "FFFFFF"),
];

// HAIR

export const HAIR_LENGTH = [
	"bald",
	"short",
	"neck",
	"shoulder",
	"upper back",
	"lower back",
	"butt",
	"thigh",
	"shin",
	"ankle",
];
export const HAIR_STYLE = [
	new HairStyle("bald", [
		"short",
		"neck",
		"shoulder",
		"upper back",
		"lower back",
		"butt",
		"thigh",
		"shin",
		"ankle",
	]),
	new ShortHairStyle("scraggy"),
	new ShortHairStyle("loose"),
	new ShortHairStyle("wavy"),
	new ShortHairStyle("bob"),
	new NeckHairStyle("curly"),
	new NeckHairStyle("ponytail", "ponytails"),
	new NeckHairStyle("bun", "buns"),
	new ShoulderHairStyle("drill", "drills"),
];
export const HAIR_ACCESSORY = [
	new HairAccessory("headband", "headbands"),
	new HairAccessory("clip", "clips"),
	new HairAccessory("tie", "ties"),
	new HairAccessory("flower", "flowers"),
	new HairAccessory("barrette", "barrettes"),
	new HairAccessory("wreath", "wreaths"),
	new HairAccessory("crown", "crowns"),
	new HairAccessory("tiara", "tiaras"),
];

// EYES

export const EYESIGHT = ["very poor", "poor", "ok", "good", "great", "perfect"];
export const PUPIL_SHAPE = ["round", "square", "slit", "shattered"];

// FAVORITES

export const FAVORITE_COLOR = [
	"white",
	"yellow",
	"blue",
	"red",
	"green",
	"black",
	"brown",
	"azure",
	"ivory",
	"teal",
	"silver",
	"purple",
	"navy blue",
	"pea green",
	"gray",
	"orange",
	"maroon",
	"charcoal",
	"aquamarine",
	"coral",
	"fuchsia",
	"wheat",
	"lime",
	"crimson",
	"khaki",
	"hot pink",
	"magenta",
	"olden",
	"plum",
	"olive",
	"cyan",
];
export const FAVORITE_ANIMAL = [
	"Baboon",
	"Badger",
	"Bat",
	"Cat",
	"Crab",
	"Deer",
	"Eagle",
	"Frog",
	"Goat",
	"Hawk",
	"Hyena",
	"Lizard",
	"Octopus",
	"Owl",
	"Raven",
	"Scorpion",
	"Spider",
	"Vulture",
	"Weasel",
	"Blood hawk",
	"Flying snake",
	"Horse",
	"Normal snake",
	"Dog",
	"Boar",
	"Constrictor snake",
	"Panther",
	"Pseudo-dragon",
	"Wolf",
	"Ape",
	"Bear",
	"Cockatrice",
	"Crocodile",
	"Shark",
	"Baby dragon",
	"Death dog",
	"Dire wolf",
	"Giant eagle",
	"Giant octopus",
	"Hippogriff",
	"Lion",
	"Tiger",
	"Dragon Wyrmling",
	"Gargoyle",
	"Giant constrictor snake",
	"Griffon",
	"Pegasus",
	"Plesiosaurus",
	"Polar bear",
	"Rhino",
	"Saber-toothed tiger",
	"Wererat",
	"Basilisk",
	"Giant scorpion",
	"Hell hound",
	"Killer whale",
	"Manticore",
	"Minotaur",
	"Owlbear",
	"Phase spider",
	"Werewolf",
	"Couatl",
	"Elephant",
	"Were tiger",
	"Gorgon",
	"Salamander",
	"Triceratops",
	"Unicorn",
	"Werebear",
	"Chimera",
	"Mammoth",
	"Medusa",
	"Vrock",
	"Wyvern",
	"Young Dragon",
	"Giant ape",
	"Hezrou",
	"Hydra",
	"Spirit Naga",
	"Tyrannosaurus Rex",
	"Glabrezu",
	"Aboleth",
	"Behir",
	"Gynosphinx",
	"Remorhaz",
	"Roc",
	"Adult dragon",
	"Purple worm",
	"Androsphinx",
	"Dragon turtle",
	"Ancient dragon",
	"Kraken",
	"Terrasque",
	"Can't decide, there's too many good ones",
	"I don't care much for animals",
	"I don't like animals",
	"Honestly, I really consider myself an animal",
	"Gets really uncomfortable when topic is brought up",
	"Duck",
	"Ancient Rainbow-dragon-sphinx",
];

// HOBBIES

export const HOBBIES = [
	"antiquing",
	"aquascaping",
	"archery",
	"art restoration",
	"astrology",
	"astronomy",
	"bagpipe repair",
	"ballet",
	"beekeeping",
	"birding",
	"bonsai",
	"book binding",
	"bread making",
	"cabaret",
	"calligraphy",
	"canoeing",
	"candle making",
	"card tricks",
	"cartography",
	"cheese making",
	"chess",
	"Dragon's Chess",
	"coffee brewery",
	"coin making",
	"confectionary",
	"composting",
	"cricket farming",
	"cryptography",
	"dowsing",
	"dynamite fishing",
	"embroidery",
	"fart harvesting",
	"ferret racing",
	"flower arranging",
	"fly tying",
	"furniture building",
	"gardening",
	"genealogy",
	"ginger bread house making",
	"glassblowing",
	"gold panning",
	"hair braiding",
	"herbalism",
	"herp keeping",
	"home brewing",
	"horseback riding",
	"houseplant care",
	"hula hooping",
	"interior design",
	"jewelry making",
	"jigsaw puzzles",
	"journaling",
	"juggling",
	"kite flying",
	"knitting",
	"kombucha brewing",
	"lace making",
	"lapidary",
	"leather working",
	"macrame",
	"mixology",
	"music history",
	"mycology",
	"nail art",
	"origami",
	"painting",
	"palmistry",
	"parkour",
	"phillumeny",
	"pickling",
	"pressed flower craft",
	"prime number hunting",
	"pottery",
	"quilting",
	"rapping",
	"rock tumbling",
	"rose gardening",
	"scrapbooking",
	"sculpting",
	"scutephily",
	"sewing",
	"shoemaking",
	"slacklining",
	"snowshoeing",
	"soap making",
	"spelunking",
	"stone skipping",
	"sword swallowing",
	"tailoring",
	"tarot",
	"taxidermy",
	"topiary",
	"upholstery",
	"wax sculpting",
	"weaving",
	"whale watching",
	"whittling",
	"whistling",
	"yodeling",
	"yoga",
	"zoology",
];

// FEARS

export const FEAR_LEVEL = [
	"deathly",
	"extreme",
	"strong",
	"mild",
	"weak",
	"minimal",
];
export const FEARS = [
	"being identified by law enforcement, as the they are currently a fugitive",
	"being discovered masquerading as a member of the opposite sex",
	"not being liked by everyone",
	"not living up to everyone's expectations",
	"being killed by a random skirmish",
	"being discovered for cheating at gambling",
	"being discovered for robbing drunk citizens at night",
	"being discovered for killing travelers",
	"being replaced by someone more competent",
	"being swindled out of money",
	"being discovered as the murderer of the local [Shop Kind] owner who's body is rotting nearby",
	"being beaten by a rival",
	"losing their good reputation",
	"being killed by a rogue that was cheated",
	"being arrested for illegal activity",
	"losing their livelihood",
	"being robbed",
	"the wrath of [Random Deity]",
	"followers of [Random Deity]",
	"magic",
	"the voices in their head",
	"being convicted of a crime they didn't commit",
	"rats and rodents",
	"the end of the world",
	"someone targeting them with spells",
	"women's undergarments",
	"anyone missing an eye",
	"being poisoned",
	"clowns and court jesters",
	"the eternal slumber that is death that will consume them eventually",
	"insects",
	"enchantment magic",
	"illusion magic",
	"Debuff spells",
	"one day discovering that they're crazy",
	"damage to their property",
	"aberrations",
	"undead",
	"fey",
	"elementals",
	"Drow",
	"Duergar",
	"Orcs",
	"Goblins",
	"Kobolds",
	"Gnomes",
	"Elves",
	"Halflings. Small hands, smell like cabbage...",
	"ghosts",
	"thunder and lightning",
	"drowning",
	"fire",
	"darkness",
	"outsiders",
	"sorcerers",
	"divine magic",
	"snakes",
	"spiders",
	"enclosed spaces",
	"Tieflings",
	"that someone will take/steal the strange crystal that fell from the sky near their house",
	"that someone will read their diary",
	"losing a precious family heirloom",
	"that their loved one won't come back from the war",
	"catching bad luck from a foreigner",
	"catching disease from a Lizardfolk, Tiefling, Dwarf, or Halfling",
	"being bewitched by a Drow",
	"witches (female spellcasters)",
	"having their luck stolen by a halfling",
	"being trampled by a horse",
	"being shot by a crossbow",
	"being killed in a brawl",
	"law enforcement",
	"the town mortician/undertaker",
	"those with an obvious physical deformity",
	"the sight and smell of blood",
	"large flocks or swarms of creatures",
	"sharp teeth and apex predators",
	"that a child is definitely a goblin in disguise, there is no way of knowing for sure, so we best just keep kids at bay",
	"facing south while drinking a liquid, lest their heart will stop like mother’s did",
	"the moonlight",
	"not being remembered",
	"public embarrassment",
	"being shown up by the opposite sex",
	'a terrifying specter, known only as "The Boogeyman"',
	"having a dog sicced on them",
	"being made to drink unsavory substances",
	"swimming",
	"heartbreak. Never again...",
	"illness of any kind",
	"being swindled or tricked",
	"being laughed at",
	"whoever was here just before you- they were bone-chillingly terrifying",
	"any other race",
	"losing social standing with the royal family",
	"getting discovered for having recently murdered someone",
	"being wrong or incorrect about anything",
	"growing old and fragile",
	"tests. Of any kind",
];
